# SPDX-License-Identifier: GPL-2.0-only
obj-m += n71-pcie-diagnostic.o
obj-m += n71-wlan-power-diagnostic.o
obj-m += n71-hdq-gpio-observe.o
obj-m += n71-i2c-topology-observe.o
obj-m += n71-pmgr-power-observe.o
obj-m += n71-i2c-power-diagnostic.o
ccflags-y += -Werror
